Gregorio development
gasigala/SPS_gregorio_sigala pull request #1
Opened 2021-02-25 17:48 UTC by gasigala

2021-02-26 04:59 UTC, kboni-tc requested changes
Great first pull request!

2021-02-26 04:59 UTC, kboni-tc commented on portfolio/src/main/webapp/index.html
> +      <img src = "images/me.jpeg" width="500" height="600"/>
Add an alt text. From Google HTML/CSS guide: "For images that means use of meaningful alternative text (alt) and for video and audio transcripts and captions, if available." (https://google.github.io/styleguide/htmlcssguide.html#Multimedia_Fallback)

2021-02-26 04:59 UTC, kboni-tc commented on portfolio/src/main/webapp/index.html
> +      <!-- TODO ADD hyper links-->
Append action Items after a colon as in TODO: action item. From Google HTML/CSS guide: https://google.github.io/styleguide/htmlcssguide.html#Action_Items.

2021-02-26 04:59 UTC, kboni-tc commented on portfolio/src/main/webapp/index.html
> +      <p>Software product sprint is the first major project that I've worked on however, you can find me on linked-in
It would be awesome if you included a link to your LinkedIn and Github here!

2021-02-26 04:59 UTC, kboni-tc commented on portfolio/src/main/webapp/style.css
> +.picture_stlye{
Should this be picture_style?

2021-02-26 22:33 UTC, gasigala commented on portfolio/src/main/webapp/index.html
> +      <p>Software product sprint is the first major project that I've worked on however, you can find me on linked-in
Done!

2021-02-28 17:34 UTC, gasigala commented on portfolio/src/main/webapp/style.css
> +.picture_stlye{
No, I was trying to format my pictures in misguided way before I used float.

2021-03-02 04:18 UTC, kboni-tc commented
Thanks for responding to the feedback so quickly! I think you still need to push your changes requested in the previous review , then I will approve and you can merge. :)

2021-03-03 04:54 UTC, gasigala commented
Sorry about that, should be all good now.

2021-03-04 02:32 UTC, kboni-tc approved these changes

2021-03-04 21:38 UTC, merged